#!/bin/bash

# Author: Ruairi O Brien
# 15-February-2013
# Script to launch and hide implementation of other scripts used to automate testign of fsUtils

source WORKING/definitions.sh 

function pause() {
	read -p "$*"
}

function SetUpDirectories() {
	mkdir -p $CODE_DIR;
	mkdir -p $CONFIGS_DIR;
	mkdir -p $DTL_FILE_INPUT_DIR;
	mkdir -p $REPORTS_DIR;
	mkdir -p $TEST_OUTPUT_DIR;
}

# Copy any DTL files that may have been generated by the fsscan within this application 
function CopyGeneratedDTLFiles {
	read -p "Would you like to copy all DTL files from previous scans (if they exist) in the the DTL input folder for report generation?(y/n)";
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		rsync -aq $OUTPUT_DIR/$DTL_FILE_DIR/ $DTL_FILE_INPUT_DIR;
	fi
}
 

echo "This script should be modified with values specific to this current test e.g. the FSMA JIRA Number."
echo "Current values: Jira number = $FSMA_JIRA_NUM."

read -p "Would you like to continue?(y/n)"
[ $REPLY == "y" ] || [ $REPLY == "N" ] || exit

# User should be sudo
if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi


SetUpDirectories

read -p "Run developer test script i.e. compile and run fsscan outputting results to OUTPUTS directory?(y/n)"
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		sudo $WORKING_DIR/developer_test.sh 
		CopyGeneratedDTLFiles
	fi

read -p "Run fsReport test script i.e. compile and run fsReport outputting results to OUTPUTS directory?(y/n)"
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		sudo $WORKING_DIR/report.sh		
	fi

exit $?
