#!/bin/bash

# Author: Ruairi O Brien
# 15-February-2013
# Script to launch and hide implementation of other scripts used to automate testign of fsUtils

source WORKING/definitions.sh 

function pause() {
	read -p "$*"
}

function SetUpDirectories() {
	mkdir -p $CODE_DIR;
	mkdir -p $CONFIGS_DIR;
	mkdir -p $DTL_FILE_INPUT_DIR;
	mkdir -p $REPORTS_DIR;
	mkdir -p $TEST_OUTPUT_DIR;
}

# Copy any DTL files that may have been generated by the fsscan within this application 
function CopyGeneratedDTLFiles {
	read -p "Would you like to copy all DTL files from previous scans (if they exist) in the the DTL input folder for report generation?(y/n)";
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		cp $OUTPUT_DIR/$DTL_FILE_DIR/* $DTL_FILE_INPUT_DIR;
	fi
}
 

echo "WARNING... If your not running this script with elevated permissons i.e. sudo, su, root whatever.. it will blow up in your face."


SetUpDirectories
chmod -R 777 WORKING

echo 'Select action:'
echo '1 - Scans'
echo '2 - Reports'
read -p '(1/2)?'

if [ $REPLY == "1" ]; 
then
	$WORKING_DIR/developer_test.sh 
	CopyGeneratedDTLFiles
	read -p "Run fsReport test script i.e. compile and run fsReport outputting results to OUTPUTS directory?(y/n)"
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		$WORKING_DIR/report.sh		
	fi

elif [ $REPLY == "2" ];
then
	$WORKING_DIR/report.sh
else	
 echo 'Wrong input... exiting because I was too lazy to implement an input loop.'	
fi


exit $?
