#!/bin/bash

# Author: Ruairi O Brien
# 15-February-2013
# Script to launch and hide implementation of other scripts used to automate testign of fsUtils

source WORKING/definitions.sh 

function pause() {
	read -p "$*"
}

function SetUpDirectories() {	
	mkdir -p $CONFIGS_DIR;
	mkdir -p $DTL_FILE_INPUT_DIR;
	mkdir -p $REPORTS_DIR;
	mkdir -p $TEST_OUTPUT_DIR;
}

function SetUpEnvironment(){
	
}

function InstallRequirement(){
	local package_manager=apt-get;
	command -v $package_manager install $1 >/dev/null 2>&1 || { $package_manager=yum };
	command -v $package_manager install $1 >/dev/null 2>&1 || { echo >&2 "Can't figure out what your package manager is. This script may not work if required programs are not installed." };
}

#Pull fsUtils code in to WORKING directory if it's not there already.
function GetFsUtilsCode(){
	local sourceControl=svn;
	command -v $sourceControl >/dev/null 2>&1 || { InstallRequirement $sourceControl };
	mkdir -p $CODE_DIR;
	$sourceControl co https://cksvnprd01.corp.emc.com/svn/gs_cork/gssd/branches/TopCoder-Contests-Review/fsUtils/ \ $CODE_DIR;	
}

# Copy any DTL files that may have been generated by the fsscan within this application 
function CopyGeneratedDTLFiles() {
	read -p "Would you like to copy all DTL files from previous scans (if they exist) in the the DTL input folder for report generation?(y/n)";
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		cp $OUTPUT_DIR/$DTL_FILE_DIR/* $DTL_FILE_INPUT_DIR;
	fi
}
 

echo "WARNING... If your not running this script with elevated permissons i.e. sudo, su, root whatever.. it will blow up in your face."


SetUpDirectories
if [ ! -d $CODE_DIR ];
then
	GetFsUtilsCode
fi
chmod -R 777 WORKING

echo 'Select action:'
echo '1 - Scans'
echo '2 - Reports'
echo '3 - Update fsUtils Source (This will delete all old code and executables)'
read -p '(1/2)?'

if [ $REPLY == "1" ]; 
then
	$WORKING_DIR/developer_test.sh 
	CopyGeneratedDTLFiles
	read -p "Run fsReport test script i.e. compile and run fsReport outputting results to OUTPUTS directory?(y/n)"
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
		$WORKING_DIR/report.sh		
	fi

elif [ $REPLY == "2" ];
then
	$WORKING_DIR/report.sh
elif [ $REPLY == "2" ];
then
	GetFsUtilsCode
else	
 echo 'Wrong input... exiting because I was too lazy to implement an input loop.'	
fi


exit $?
